# Generated by Django 5.0.3 on 2024-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('precio', models.FloatField(verbose_name=5)),
                ('stock', models.IntegerField(verbose_name=7)),
            ],
        ),
    ]
